web:
  build: .
  container_name: web
  volumes:
    - /srv/docker/web:/var/www/web
  ports:
    - 80:80
  links:
    - db

db:
  image: mysql
  container_name: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=PE0NBl3mKnQVgNCM
  volumes:
    - /srv/docker/mysql:/var/lib/mysql
